-- Admin-confirmed burner / technical identities for Data Hub parsers.
-- Scope is source-specific so an alias ignored in GA is not silently ignored elsewhere.

create table if not exists public.ignored_identities (
  id bigint generated by default as identity primary key,
  source_type text not null,
  alias_type text not null default 'other',
  alias_value text not null,
  normalized_value text not null,
  reason text not null default 'burner_or_technical_account',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source_type,alias_type,normalized_value)
);

create index if not exists ignored_identities_lookup_idx
  on public.ignored_identities(source_type,normalized_value);

alter table public.ignored_identities enable row level security;
revoke all on table public.ignored_identities from anon,authenticated;
revoke all on sequence public.ignored_identities_id_seq from anon,authenticated;
