-- Store Card projection movement snapshots
-- Used server-side by player-store-card to compare leaderboard state between relevant imports.

create table if not exists public.store_card_projection_snapshots (
  id bigint generated by default as identity primary key,
  month date not null,
  import_id uuid references public.imports(id) on delete set null,
  report_type text,
  import_created_at timestamptz,
  leaderboard jsonb not null check (jsonb_typeof(leaderboard) = 'array'),
  team_effort_estimate_percent numeric,
  captured_at timestamptz not null default now(),
  unique (month, import_id)
);

create index if not exists store_card_projection_snapshots_month_captured_idx
  on public.store_card_projection_snapshots(month, captured_at desc);

alter table public.store_card_projection_snapshots enable row level security;

-- No browser role needs direct access. The player-store-card Edge Function uses
-- its server-side service role and returns only the movement fields required by the UI.
revoke all on table public.store_card_projection_snapshots from anon, authenticated;
