-- Team Rating questionnaire source for Store Card People score.
-- Canonical responses are deduplicated by respondent/month/timestamp.
-- Votes from self-voting or out-of-month responses are not counted.

create table if not exists public.team_rating_responses (
  id uuid primary key default gen_random_uuid(),
  response_key text not null unique,
  response_month date not null,
  submitted_at timestamptz not null,
  respondent_email text,
  respondent_person_id uuid references public.people(id) on delete set null,
  import_id uuid references public.imports(id) on delete set null,
  is_valid boolean not null default true,
  disqualified_reason text,
  raw_vote_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists team_rating_responses_month_person_idx
  on public.team_rating_responses(response_month, respondent_person_id, submitted_at desc);

create table if not exists public.team_rating_votes (
  id bigint generated by default as identity primary key,
  response_id uuid not null references public.team_rating_responses(id) on delete cascade,
  response_month date not null,
  respondent_person_id uuid references public.people(id) on delete set null,
  nominee_person_id uuid references public.people(id) on delete set null,
  nominee_raw text not null,
  question_index integer not null,
  import_id uuid references public.imports(id) on delete set null,
  is_valid boolean not null default true,
  created_at timestamptz not null default now(),
  unique(response_id, question_index)
);

create index if not exists team_rating_votes_month_nominee_idx
  on public.team_rating_votes(response_month, nominee_person_id)
  where is_valid is true;

alter table public.team_rating_responses enable row level security;
alter table public.team_rating_votes enable row level security;

revoke all on table public.team_rating_responses from anon, authenticated;
revoke all on table public.team_rating_votes from anon, authenticated;
revoke all on sequence public.team_rating_votes_id_seq from anon, authenticated;
