-- Universal Metric Import aliases
-- Same visible metric name can map differently by scope and granularity.
-- Example: POFR PERSON/week -> perfect_order_fulfilment_ratio,
--          POFR STORE/month -> store_pofr.

create table if not exists public.metric_aliases (
  id bigint generated by default as identity primary key,
  alias text not null,
  normalized_alias text not null,
  metric_id text not null references public.metric_definitions(metric_id) on delete cascade,
  scope text not null check (scope in ('person','store')),
  granularity text not null default 'any' check (granularity in ('any','day','week','month')),
  priority integer not null default 100,
  confirmed boolean not null default true,
  active boolean not null default true,
  source text not null default 'manual',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists metric_aliases_mapping_uq
  on public.metric_aliases(normalized_alias,metric_id,scope,granularity);

create index if not exists metric_aliases_lookup_idx
  on public.metric_aliases(normalized_alias,scope,granularity)
  where active is true;

alter table public.metric_aliases enable row level security;
revoke all on table public.metric_aliases from anon,authenticated;
revoke all on sequence public.metric_aliases_id_seq from anon,authenticated;

-- Seed aliases are intentionally conservative. metric_definitions.label and
-- metric_id are also implicit aliases inside parse-universal-metrics.
-- Additional confirmed aliases can be added without changing parser code.
