import { createClient } from "npm:@supabase/supabase-js@2";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const defs=[
["avg_picking_time","Avg Picking Time","number"],["avg_packing_time","Avg Packing Time","number"],["picking_app_task_count","Picking App Task Count","count"],["items_picked_via_scanner_ratio","Items Picked Via Scanner Ratio","percent"],["item_count_total","Item Count Total","count"],["missing_incorrect_items_count","Missing Incorrect Items Count","count"],["missing_incorrect_items_rate","Missing Incorrect Items Rate","percent"],["not_collected_items_ratio","Not Collected Items Ratio","percent"],["perfect_order_fulfilment_ratio","Perfect Order Fulfilment Ratio","percent"],["average_rating_of_goods","Average Rating of Goods","number"],["purchases_missing_replaced_count","Purchases with Missing or Replaced Items Count","count"],["merchant_rejection_ratio","Merchant Rejection Ratio","percent"],["venue_late_preparation_ratio","Venue Late Preparation Ratio","percent"],["bad_goods_rating_ratio","Bad Goods Rating Ratio","percent"],["venue_related_cs_tickets_ratio","Venue Related CS Tickets Ratio","percent"],["refund_percent","Refund %","percent"],["picking_time_per_item","Picking time per item","number"],["packing_time_per_item","Packing time per item","number"],["avg_items_per_order","Avg Items Per Order","number"]
];
function val(s:string){s=s.trim();if(s==="∅"||!s)return null;const n=Number(s.replace(/,/g,"").replace("%",""));return Number.isFinite(n)?n:null}
function parse(text:string){const rows:any[]=[];for(const line of text.split(/\n/)){if(!/^\d+\s*\|/.test(line.trim()))continue;const a=line.split("|").map(x=>x.trim());if(a.length<21)continue;rows.push({alias:a[1],values:a.slice(2,21).map(val)})}
const g=text.match(/Generated by Looker on ([A-Za-z]+) (\d{1,2}), (20\d{2})/i);let ps=null,pe=null;if(g){const d=new Date(`${g[1]} ${g[2]}, ${g[3]} 12:00:00 UTC`),day=d.getUTCDay()||7,mon=new Date(d);mon.setUTCDate(d.getUTCDate()-day-6);const sun=new Date(mon);sun.setUTCDate(mon.getUTCDate()+6);ps=mon.toISOString().slice(0,10);pe=sun.toISOString().slice(0,10)}return{rows,ps,pe}}
function finite(v:any){if(v===null||v===undefined||v==="")return null;const x=Number(v);return Number.isFinite(x)?x:null}
function sumMetric(rows:any[],idx:number){
 let total=0,any=false;
 for(const r of rows){const v=finite(r.values?.[idx]);if(v!==null){total+=v;any=true}}
 return any?total:null;
}
function weightedMetric(rows:any[],idx:number,weightIdx:number){
 let num=0,den=0;const vals:number[]=[];
 for(const r of rows){
  const v=finite(r.values?.[idx]);if(v===null)continue;vals.push(v);
  const w=finite(r.values?.[weightIdx]);if(w!==null&&w>0){num+=v*w;den+=w}
 }
 if(den>0)return num/den;
 return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;
}
function mergeGaRows(rows:any[],person_id:string){
 const aliases=[...new Set(rows.map((r:any)=>r.alias).filter(Boolean))];
 const values:any[]=[];
 // indexes: task count=2, item count=4, missing count=5, purchase issue count=10
 const countIdx=new Set([2,4,5,10]);
 const itemWeightedIdx=new Set([3,6,16,17]);
 for(let i=0;i<defs.length;i++){
  if(countIdx.has(i))values[i]=sumMetric(rows,i);
  else if(itemWeightedIdx.has(i))values[i]=weightedMetric(rows,i,4);
  else values[i]=weightedMetric(rows,i,2);
 }
 return {alias:aliases.join(" + "),aliases,person_id,values,merged_alias_count:aliases.length};
}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});try{
const auth=req.headers.get("Authorization");if(!auth)return J({error:"Missing authorization"},401);
const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});
const {data:{user}}=await userClient.auth.getUser();if(!user)return J({error:"Unauthorized"},401);
const {data:admin}=await userClient.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();if(!admin)return J({error:"Admin access required"},403);
const db=createClient(url,service);
const {import_id,extracted_text,mode="preview"}=await req.json();if(!import_id||typeof extracted_text!=="string")return J({error:"Missing import_id or extracted_text"},400);
const {data:imp,error:ie}=await db.from("imports").select("*").eq("id",import_id).single();if(ie||!imp)return J({error:"Import not found",detail:ie?.message},404);
const p=parse(extracted_text);if(!p.rows.length)return J({error:"No GA rows detected"},422);
const norm=(s:string)=>s.trim().toLowerCase();
const compact=(s:string)=>norm(s).replace(/[^a-z0-9]+/g,"");
const isTechnicalIdentity=(s:string)=>{const x=compact(s);return x==="woltmark"||x.startsWith("woltmarketholesovice")};
const isOutOfStoreIdentity=(s:string)=>compact(s)==="nicksch";
const technicalRows=p.rows.filter((r:any)=>isTechnicalIdentity(r.alias)||isOutOfStoreIdentity(r.alias));
const candidateRows=p.rows.filter((r:any)=>!isTechnicalIdentity(r.alias)&&!isOutOfStoreIdentity(r.alias));
const {data:persistentIgnored,error:ignoreErr}=await db.from("ignored_identities").select("normalized_value").eq("source_type","ga_metrics");
if(ignoreErr)return J({error:"Ignored identity lookup failed",detail:ignoreErr.message},500);
const ignoredSet=new Set((persistentIgnored||[]).map((x:any)=>norm(x.normalized_value)));
const burnerRows=candidateRows.filter((r:any)=>ignoredSet.has(norm(r.alias)));
const ignoredRows=[...technicalRows,...burnerRows];
const humanRows=candidateRows.filter((r:any)=>!ignoredSet.has(norm(r.alias)));
const names=humanRows.map((r:any)=>r.alias);
const aliasLookup=names.length
  ?await db.from("person_aliases").select("person_id,alias_value,normalized_value,confirmed").in("normalized_value",names.map(norm))
  :{data:[],error:null};
const ars=aliasLookup.data,ae=aliasLookup.error;
if(ae)return J({error:"Identity lookup failed",detail:ae.message},500);
const amap=new Map();for(const a of ars||[])if(a.confirmed!==false)amap.set(norm(a.normalized_value||a.alias_value),a.person_id);
const unresolved=[...new Set(names.filter((x:string)=>!amap.has(norm(x))))];
const grouped=new Map<string,any[]>();
for(const r of humanRows){
 const pid=amap.get(norm(r.alias));if(!pid)continue;
 if(!grouped.has(pid))grouped.set(pid,[]);
 grouped.get(pid)!.push(r);
}
const mergedRows=[...grouped.entries()].map(([pid,rows])=>mergeGaRows(rows,pid));
if(mode==="preview")return J({
  ok:true,preview:true,parser_stage:"ga_metrics_parsed_v7_identity_merge",
  import_id,filename:imp.filename,period_start:p.ps,period_end:p.pe,
  parsed_row_count:p.rows.length,
  people_count:mergedRows.length+unresolved.length,
  matched_count:mergedRows.length,
  merged_identity_count:mergedRows.filter((x:any)=>x.merged_alias_count>1).length,
  merged_identities:mergedRows.filter((x:any)=>x.merged_alias_count>1).map((x:any)=>x.aliases),
  metric_count:defs.length,
  observation_count:mergedRows.length*defs.length,
  unresolved,
  ignored_identities:ignoredRows.map((r:any)=>r.alias),
  people:[
   ...mergedRows.map((r:any)=>({source_identity:r.alias,source_identities:r.aliases,person_id:r.person_id,values:Object.fromEntries(defs.map((d,i)=>[d[0],r.values[i]]))})),
   ...humanRows.filter((r:any)=>!amap.has(norm(r.alias))).map((r:any)=>({source_identity:r.alias,person_id:null,values:Object.fromEntries(defs.map((d,i)=>[d[0],r.values[i]]))}))
  ],
  message:"Schema-correct DB identity preview. Old/new picker logins are merged per person; technical/non-Holešovice identities are excluded."
});
if(mode!=="commit")return J({error:"Unknown mode"},400);
if(unresolved.length)return J({error:"Unresolved identities",detail:unresolved.join(", "),unresolved},409);
const keys=defs.map(d=>d[0]);const {data:md,error:me}=await db.from("metric_definitions").select("metric_id").in("metric_id",keys);if(me)return J({error:"Metric lookup failed",detail:me.message},500);
const have=new Set((md||[]).map((x:any)=>x.metric_id)),missing=keys.filter(k=>!have.has(k));if(missing.length)return J({error:"Missing metric definitions",detail:missing.join(", ")},409);
const obs:any[]=[];for(const r of mergedRows)for(let i=0;i<defs.length;i++){const d=defs[i],person_id=r.person_id,v=r.values[i];if(v===null||v===undefined)continue;obs.push({person_id,metric_id:d[0],value:v,period_start:p.ps,period_end:p.pe,granularity:"week",source_type:"ga_metrics",import_id,source_record_key:`mo|ga_metrics|${person_id}|${d[0]}|${p.ps}|${p.pe}|week`,metadata:{source_identity:r.alias,source_identities:r.aliases,merged_login_rows:r.merged_alias_count,unit:d[2]}})}
const {data:w,error:we}=await db.from("metric_observations").upsert(obs,{onConflict:"source_record_key"}).select("id");if(we)return J({error:"Observation write failed",detail:we.message},500);
const {error:ue}=await db.from("imports").update({status:"imported",period_start:p.ps,period_end:p.pe,parser_version:"ga-metrics-v12"}).eq("id",import_id);if(ue)return J({error:"Import status update failed",detail:ue.message},500);
return J({ok:true,preview:false,parser_stage:"ga_metrics_committed_v7",import_id,period_start:p.ps,period_end:p.pe,attempted_count:obs.length,inserted_count:w?.length??0,merge_guard:"canonical-v152",ignored_identities:ignoredRows.map((r:any)=>r.alias)});
}catch(e){return J({error:"Function error",detail:e instanceof Error?e.message:String(e)},500)}});
